# Generated by Django 4.1.5 on 2023-03-06 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_komment'),
    ]

    operations = [
        migrations.AddField(
            model_name='komment',
            name='mahsulot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.mahsulot'),
        ),
    ]
