# Generated by Django 4.1.5 on 2023-03-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_komment_sana_alter_komment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='wished',
            field=models.BooleanField(default=False),
        ),
    ]
