# Generated by Django 4.1.5 on 2023-03-10 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_myuser_username'),
        ('buyurtma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.myuser'),
        ),
        migrations.AddField(
            model_name='wishes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.myuser'),
        ),
    ]
