# Generated by Django 4.1.5 on 2023-03-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0009_savat_narx'),
    ]

    operations = [
        migrations.AddField(
            model_name='savat',
            name='umumiy',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
