# Generated by Django 4.1.5 on 2023-03-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0010_savat_umumiy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savat',
            name='narx',
        ),
    ]
