# Generated by Django 4.1.5 on 2023-03-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0013_savat_wished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='mahsulot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyurtma.savat'),
        ),
    ]
