# Generated by Django 4.1.5 on 2023-03-13 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_komment_sana_alter_komment_username'),
        ('buyurtma', '0016_alter_wishes_mahsulot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='mahsulot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiy.mahsulot'),
        ),
    ]
