# Generated by Django 4.1.5 on 2023-03-13 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_myuser_username'),
        ('buyurtma', '0017_alter_wishes_mahsulot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manzil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.SmallIntegerField()),
                ('manzil', models.TextField()),
                ('zipcode', models.SmallIntegerField()),
                ('shahar', models.TextField()),
                ('davlat', models.TextField()),
                ('asosiy', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('holat', models.TextField()),
                ('summa', models.IntegerField()),
                ('yetkaish_narxi', models.IntegerField()),
                ('manzil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyurtma.manzil')),
                ('savat', models.ManyToManyField(to='buyurtma.savat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.myuser')),
            ],
        ),
    ]
