# Generated by Django 4.1.5 on 2023-03-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0018_manzil_buyurtma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savat',
            name='wished',
        ),
    ]
